In [37]:
# import necessary ribraries
import pandas as pd
import os
import whisper
from tqdm import tqdm  # shows a progress bar

In [38]:
# Paths
audio_folder = "chichewa_voice_agent/audios"
training_csv = "chichewa_voice_agent/phrases/phrases.csv"

In [39]:
# load phrases dataset
df = pd.read_csv(training_csv)
df.head()  # check first few rows

                                        phrase  speaker audio_file
0                     Moni brother, uli bwanji  Timothy      1.wav
1                    Hello, sister muli bwanji  Timothy      2.wav
2     Good morning m'bale wanga, wazuka bwanji  Timothy      3.wav
3         Good afternoon, phone yanu sikugwira  Timothy      4.wav
4  Good evening, tsiku lanu linali bwanji lero  Timothy      5.wav

In [40]:
# create full audio path
df["audio_path"] = df["audio_file"].apply(
    lambda x: os.path.join(audio_folder, x)
)

In [41]:
# prepare dataset for Whisper
df_finetune = df[["audio_path", "phrase"]].copy()

In [42]:
# rename column to expected name
df_finetune.rename(columns={"phrase": "text"}, inplace=True)

In [43]:
# save dataset
df_finetune.to_csv("chichewa_whisper_finetune.csv", index=False)

In [44]:
print("Dataset ready for training")
df_finetune.head()

Dataset ready for training

,audio_path,text
0,chichewa_voice_agent/audios/1.wav,"Moni brother, uli bwanji"
1,chichewa_voice_agent/audios/2.wav,"Hello, sister muli bwanji"
2,chichewa_voice_agent/audios/3.wav,"Good morning m'bale wanga, wazuka bwanji"
3,chichewa_voice_agent/audios/4.wav,"Good afternoon, phone yanu sikugwira"
4,chichewa_voice_agent/audios/5.wav,"Good evening, tsiku lanu linali bwanji lero"